# Numpy( Numerical Data)
-Support to Arrys, Matrices and mathematical operations.
- N- dimentional Array
- Linear Algebra functions
- Simulation and Random sampling

In [ ]:
# Installation
#!pip install numpy
# Create an array
import numpy as np #alias

#1D Array
array1 = np.array([1,2,3,4,5,6])
print(array1)

#2D Array
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)

#zeros Array
array3 = np.zeros((3,3))
print(array3)

#Random Array
array4 = np.random.random((3,3))
print(array4)





[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.16167367 0.09571903 0.31673353]
 [0.00808128 0.3614701  0.36217139]
 [0.54034705 0.91457433 0.64060124]]


In [ ]:
#Array attributes- Shapes, size, data type

#Shapes

print(array1.shape)
print(array2.shape)

#Size
print(array1.size)
print(array2.size)

#Data Type
print(array1.dtype)
print(array2.dtype)


(6,)
(2, 3)
6
6
int64
int64


In [ ]:
#Indexing
print(array1)

print(array1[0:3])
#Slicing [Start:stop:step]
print(array1[0:6:2])

[1 2 3 4 5 6]
[1 2 3]
[1 3 5]


In [ ]:
#Broadcasting
array5 = array1 + np.array([[10],[20],[30]])
print(array5)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]]


In [ ]:
#vectorized operations
array6 = array1 + 10
print(array6)

[11 12 13 14 15 16]


In [ ]:
# 1) Create two different array of same size and perform addition, substraction, multiplication, division.

array7 = [1,2,3]
array8 = [4,5,6]
array9 = np.add(array7,array8)
array10 = np.subtract(array7,array8)
array11 = np.multiply(array7,array8)
array12 = np.divide(array7,array8)

print(array9)
print(array10)
print(array11)
print(array12)

# 2) Create 5*5 identity matrix (np.eye)

import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Broadcasting
a= np.array([[1],[2],[3]]) #shape
a
b= np.array([[10,20,30],[40,50,60],[70,80,90]]) #shape(3,3)
b

#Broadcasting addition
c= a+b
print(c)

[[11 21 31]
 [42 52 62]
 [73 83 93]]


In [ ]:
#Broadcasting multiplication
a1= np.array([[1],[2],[3]]) #shape
b1= 10 #scalar

c1= a1*b1
print(c1)

[[10]
 [20]
 [30]]
