<a href="https://colab.research.google.com/github/aina-maryam/aina-maryam/blob/main/Pandas_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy( Numerical Data)
-Support to Arrys, Matrices and mathematical operations.
- N- dimentional Array
- Linear Algebra functions
- Simulation and Random sampling

In [5]:
# Installation
# !pip install numpy
# Create an array
import numpy as np #alias

#1D Array
array1 = np.array([1,2,3,4,5,6])
print(array1)

#2D Array
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)

#zeros Array
array3 = np.zeros((3,3))
print(array3)

#Random Array
array4 = np.random.random((3,3))
print(array4)





[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.73806564 0.24242672 0.45748824]
 [0.90736698 0.17336854 0.24546336]
 [0.20829816 0.64768309 0.99878453]]


In [ ]:
#Array attributes- Shapes, size, data type

#Shapes

print(array1.shape)
print(array2.shape)

#Size
print(array1.size)
print(array2.size)

#Data Type
print(array1.dtype)
print(array2.dtype)


(6,)
(2, 3)
6
6
int64
int64


In [ ]:
#Indexing
print(array1)

print(array1[0:3])
#Slicing [Start:stop:step]
print(array1[0:6:2])

[1 2 3 4 5 6]
[1 2 3]
[1 3 5]


In [ ]:
#Broadcasting
array5 = array1 + np.array([[10],[20],[30]])
print(array5)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]]


In [ ]:
#vectorized operations
array6 = array1 + 10
print(array6)

[11 12 13 14 15 16]


In [ ]:
# 1) Create two different array of same size and perform addition, substraction, multiplication, division.

array7 = [1,2,3]
array8 = [4,5,6]
array9 = np.add(array7,array8)
array10 = np.subtract(array7,array8)
array11 = np.multiply(array7,array8)
array12 = np.divide(array7,array8)

print(array9)
print(array10)
print(array11)
print(array12)

# 2) Create 5*5 identity matrix (np.eye)

import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Broadcasting
a= np.array([[1],[2],[3]]) #shape
a
b= np.array([[10,20,30],[40,50,60],[70,80,90]]) #shape(3,3)
b

#Broadcasting addition
c= a+b
print(c)

[[11 21 31]
 [42 52 62]
 [73 83 93]]


In [ ]:
#Broadcasting multiplication
a1= np.array([[1],[2],[3]]) #shape
b1= 10 #scalar

c1= a1*b1
print(c1)

[[10]
 [20]
 [30]]


#Pandas

- Two types- Series and DataFrame.
- Series is 1D.
- DataFrame is 2D.
- Built on top of Numpy.
- Helps in data manipulation and analysis.






In [4]:
# Installation
# !pip install pandas

In [31]:
# create DataFrame
import pandas as pd

data = {'Name': ['Cyan', 'Andy', 'Noor','Rodger'],
        'Age':['27', '25','30','21'],
        'City': ['LA', 'Dallas', 'NY', 'Easton']}

df = pd.DataFrame(data)
print(df)

print(data)


     Name Age    City
0    Cyan  27      LA
1    Andy  25  Dallas
2    Noor  30      NY
3  Rodger  21  Easton
{'Name': ['Cyan', 'Andy', 'Noor', 'Rodger'], 'Age': ['27', '25', '30', '21'], 'City': ['LA', 'Dallas', 'NY', 'Easton']}


In [6]:
# view top two rows
df.head(2)

Name Age    City
0  Cyan  27      LA
1  Andy  25  Dallas

In [7]:
# view bottom two rows
df.tail(2)

Name Age    City
2    Noor  30      NY
3  Rodger  21  Easton

In [8]:
# to get basic information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      object
 2   City    4 non-null      object
dtypes: object(3)
memory usage: 224.0+ bytes


In [11]:
# Select the column
df['Name']
# Select multiple column
df[['Name','Age']]

Name Age
0    Cyan  27
1    Andy  25
2    Noor  30
3  Rodger  21

In [13]:
# Access the rows
df.iloc[1]

Name      Andy
Age         25
City    Dallas
Name: 1, dtype: object

In [34]:
# Modification in age column
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Age'] = df['Age'] + 10
print(df)
print(df['Age'].dtype)

     Name  Age    City
0    Cyan   47      LA
1    Andy   45  Dallas
2    Noor   50      NY
3  Rodger   41  Easton
int64


In [35]:
# Any missing values
df.isnull().sum()

Name    0
Age     0
City    0
dtype: int64

In [37]:
# Drop a row with missing values
df.dropna(inplace=True)


In [39]:
# Save a file
df.to_excel('data.xlsx', index=False)

In [8]:
# Create series from the list
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [9]:
# Create series from an array
s2 = pd.Series(np.array([1,2,3,4,5]))
print(s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [10]:
# Create series from a dictionary
s3 = pd.Series({'a':1, 'b':2, 'c':3})
print(s3)

a    1
b    2
c    3
dtype: int64


In [12]:
# Indexing and slicing series
print(s3['a'])

# Accessing elements by position
print(s3[0])


# Slicing
print(s3[0:2])

1
1
a    1
b    2
dtype: int64


<ipython-input-12-965ce6223e13>:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s3[0])


In [13]:
# Operations on series

# Addition
s4 = s1 + s2
print(s4)

# Subtraction
s5 = s1 - s2
print(s5)

# Multiplication
s6 = s1 * s2
print(s6)

# Division
s7 = s1 / s2
print(s7)

# Aggregation functions
print(s1.sum())
print(s1.mean())
print(s1.max())
print(s1.min())




0     2
1     4
2     6
3     8
4    10
dtype: int64
0    0
1    0
2    0
3    0
4    0
dtype: int64
0     1
1     4
2     9
3    16
4    25
dtype: int64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64
15
3.0
5
1


In [52]:
# Creating dataframe from list of lists

data = [['Alice','25'],['Bob', '6'],['Caty', '20']]
df3 = pd.DataFrame(data, columns=['Name','Age'])
print(df3)

    Name Age
0  Alice  25
1    Bob   6
2   Caty  20


In [54]:
# Indexing and slicing dataframes

# label-based indexing
print(df3.loc[0,'Name'])

# position-based indexing
print(df3.iloc[0,0])



Alice
Alice


In [58]:
# Sorting and Filtering Dataframes
import pandas as pd
df3['Age'] = pd.to_numeric(df3['Age'], errors='coerce')  # Handle potential errors
df3_sorted = df3.sort_values(by='Age')
print(df3_sorted)




    Name  Age
1    Bob    6
2   Caty   20
0  Alice   25


In [59]:
# data normalization and standardization
import pandas as pd

df3_normalized = (df3['Age'] - df3['Age'].min()) / (df3['Age'].max() - df3['Age'].min())
print(df3_normalized)

df3_standardized = (df3['Age'] - df3['Age'].mean()) / df3['Age'].std()
print(df3_standardized)

0    1.000000
1    0.000000
2    0.736842
Name: Age, dtype: float64
0    0.812277
1   -1.116881
2    0.304604
Name: Age, dtype: float64


In [60]:
# data group by and mean age
df3_grouped = df3.groupby('Age')
print(df3_grouped)

mean_age = df3_grouped['Age'].mean()
print(mean_age)


Age
6      6.0
20    20.0
25    25.0
Name: Age, dtype: float64


In [65]:
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']})
df5 = pd.DataFrame({'A': ['A3', 'A4', 'A5'], 'B': ['B3', 'B4', 'B5']})
result_row = pd.concat([df4, df5])
print(result_row)

result_column = pd.concat([df4, df5], axis=1)
print(result_column)
#

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  A3  B3
1  A4  B4
2  A5  B5
    A   B   A   B
0  A0  B0  A3  B3
1  A1  B1  A4  B4
2  A2  B2  A5  B5


In [68]:
# Joining DataFrames

# create sample dataframe
left = pd.DataFrame({'value1':[1,2,3]}, index = ['A','B','C'])
right = pd.DataFrame({'value2':[4,5,6]}, index = ['B','C','D'])
join_df = left.join(right, how='inner')
print(join_df)


   value1  value2
B       2       4
C       3       5
